use_frameworks!

platform :ios, '10.0'

target 'LYTestPodFramework_Example' do
  pod 'LYTestPodFramework', :path => '../'

  target 'LYTestPodFramework_Tests' do
    inherit! :search_paths

    
  end
end
